### ISSUE TITLE
why does this fork exist?

### ISSUE THREAD

**Issue by xronin01** [Rozmir-Rohi/mo-creatures-legacy#1]
look this https://www.curseforge.com/minecraft/mc-mods/mo-creatures-continuation

**Comment by Rozmir-Rohi** [comment]
The project is different to Mo Creatures Continuation in the following ways:
 - This project began in October 2022.
 
 - This project provides only a legacy version of Mo' Creatures and will not backport anything from newer versions of Mo' Creatures. Hence, the name "Mo' Creatures Legacy".

 - Changes Mo' Creatures entity textures to fit with default Minecraft.

 - Adds achievements for Mo' Creatures.

 - Adds death messages for Mo' Creatures pets.

 - Features integration with the following mods:
  • Thaumcraft (aspect support)
  • Et Futurum Requiem (creature taming and feeding, and biome spawns)

 - Has set a finish date (13th February 2024) where development is finalized.

You can see the list of this mod's features on Modrinth once it is released there.
