### ISSUE TITLE
[bug]The pet's name can only be entered in English

### ISSUE THREAD

**Issue by Omgise** [Rozmir-Rohi/mo-creatures-legacy#14]
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/106000018/a22c2614-fd03-48f0-bd9b-9fae31d03898)

**Comment by Rozmir-Rohi** [comment]
I'll see what I can do to fix this.

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.
