### ISSUE TITLE
[Bug] There is no durability display on the weapon tooltips

### ISSUE THREAD

**Issue by Omgise** [Rozmir-Rohi/mo-creatures-legacy#18]
mod:
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/106000018/13372b08-5a9d-47dc-87ab-477c24977b7f)
vanilla:
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/106000018/23ab92be-d0e1-4d4e-8e0e-65dc69d8ecb9)

**Comment by Rozmir-Rohi** [comment]
I'll see what I can do to fix this.

**Comment by Rozmir-Rohi** [comment]
Have you tried pressing F3 + H to enable advanced tooltips?

After pressing F3 + H I don't get this issue, see below:

![2024-01-18_23 13 38](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/120696188/ea7cbc63-cce0-4ca4-8928-83fdba949297)

**Comment by Omgise** [comment]
Is it possible to show the durability of the weapon without pressing F3+H?
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/106000018/1e53d9d5-a45f-4456-b5f5-bd0f988f99d4)
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/106000018/a0f83043-d342-41ae-b937-66faf58b86eb)

**Comment by Omgise** [comment]
https://www.curseforge.com/minecraft/mc-mods/waila

**Comment by Omgise** [comment]
I think it was this mod

**Comment by Rozmir-Rohi** [comment]
I don't think it is that one, when I loaded a world with Waila it didn't show item durability by default.

Could you try seeing if it's the Not Enough Items mod?

**Comment by Omgise** [comment]
I found it. It's the [EnderCore](https://github.com/GTNewHorizons/EnderCore) mod

**Comment by Rozmir-Rohi** [comment]
ok, thank you.
I'll see what I can do to fix the durability tooltips soon.

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.
