### ISSUE TITLE
[bug] Fix missing lang

### ISSUE THREAD

**Issue by Omgise** [Rozmir-Rohi/mo-creatures-legacy#19]
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/106000018/6ecba684-2291-4498-86b8-d88ce7af6e35)

**Comment by Rozmir-Rohi** [comment]
I'll fix this.

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.

Also, @Omgise can you please add the following to the zh_CN.lang language file based on the change to the en_US.lang file:

**Add New:**
entity.MoCreatures.ThrowableBlockForGolem.name

Thanks

**Comment by Omgise** [comment]
Ok, I'll add it soon
