### ISSUE TITLE
The mod crash on server startup

### ISSUE THREAD

**Issue by quentin452** [Rozmir-Rohi/mo-creatures-legacy#21]
## What is the Bug?

The mod crash on server startup

## How can I Reproduce this Bug?
Examples:
* Use MoCreatures-Legacy-Beta-1.1
* Happens when startup

## Crash Report

[crash-2024-01-18_21.30.04-server.txt](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/13981394/crash-2024-01-18_21.30.04-server.txt)

**Comment by Rozmir-Rohi** [comment]
I'll see what I can do to fix this.

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.

As you can probably tell, this project hasn't been tested on servers before.
If you have time and would like to contribute, could you do a test of the mod's features on a server when the next beta version is released? If so please report any bugs you find.

I've already found that pet death messages don't show on servers, and I don't think there is anything I can do to fix them on servers.

**Comment by quentin452** [comment]
> Fixed issue with recent commit.
> 
> As you can probably tell, this project hasn't been tested on servers before. If you have time and would like to contribute, could you do a test of the mod's features on a server when the next beta version is released? If so please report any bugs you find.
> 
> I've already found that pet death messages don't show on servers, and I don't think there is anything I can do to fix them on servers.

i don't have really alot of times to contribute because i update my mods/modpacks
