### ISSUE TITLE
DUDUDUDU max verstappen

### ISSUE THREAD

**Issue by oskarthegoldenegg** [Rozmir-Rohi/mo-creatures-legacy#23]
## add max
he verstappen

## he really cool
his theme is fire

## he belgian
just like them fries

## please
im begging you

**Comment by Rozmir-Rohi** [comment]
I'm assuming you want me to add "33 Max Verstappen" by Carte Blanq and Maxx Power as a music disc.

I won't be adding this to Mo'Creatures Legacy as it doesn't relate to the Mo' Creatures mod.

But I might create another mod with this feature if my request to use parts of "33 Max Verstappen" gets approved by Carte Blanq.

**Comment by Rozmir-Rohi** [comment]
It's been more than a week since I requested permission from Carte Blanq to use parts of "33 Max Verstappen" to create a mod with this feature and I haven't had a reply from them.
Because of this, I won't be making another mod with this feature.
