### ISSUE TITLE
[bug]The name of the kitty bed cannot be changed through the lang file

### ISSUE THREAD

**Issue by Omgise** [Rozmir-Rohi/mo-creatures-legacy#24]
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/106000018/1fd05824-3666-4cbd-82bf-d7e80ddb3b91)

**Comment by Rozmir-Rohi** [comment]
I'll see what I can do to fix this.

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.

Also @Omgise, can you please update the zh_CN.lang language file based on the following changed to the en_US.lang file:

**Remove:** item.kittybed.name

**Add:**
	item.kittybed.black.name
	item.kittybed.red.name
	item.kittybed.green.name
	item.kittybed.brown.name
	item.kittybed.blue.name
	item.kittybed.purple.name
	item.kittybed.cyan.name
	item.kittybed.silver.name
	item.kittybed.gray.name
	item.kittybed.pink.name
	item.kittybed.lime.name
	item.kittybed.yellow.name
	item.kittybed.lightBlue.name
	item.kittybed.magenta.name
	item.kittybed.orange.name
	item.kittybed.white.name 

Thanks

**Comment by Omgise** [comment]
Finish
