### ISSUE TITLE
Entity ID Conflict Crash [CAUSED BY replaceVanillaCreepers=TRUE     and     replaceWitcheryWerewolfEntities=TRUE]

### ISSUE THREAD

**Issue by brandyyn** [Rozmir-Rohi/mo-creatures-legacy#39]
Just wanted to make this post as a PSA because the setting is on by default, this setting may cause an entity id crash when playing with other mods, here's my crash. This is an easy fix that the log/crash report doesn't really communicate well.

[crash-2024-02-14_07.43.29-client.txt](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/14276610/crash-2024-02-14_07.43.29-client.txt)

setting [replaceVanillaCreepers=false] fixes this

   > THIS MAY BE INCOMPATIBLE WITH OTHER MODS THAT DO THINGS WITH CREEPERS - If true: will replace vanilla creepers in worlds with own extension of creeper code. This is used to make creepers scared of kitty. If this is causing problems with other mods set this to false to turn it off.
   > B:replaceVanillaCreepers=false

**Comment by Rozmir-Rohi** [comment]
This actually helped me find another bug -  replaceWitcheryWerewolfEntities being dependent on replaceVanillaCreepers.

In the real final version (which will be released today),  replaceWitcheryWerewolfEntities may also need to be set to false.

**Comment by brandyyn** [comment]
> This issue definitely happens when the **RPGInventory mod is installed** with Mo' Creature's Legacy.
> 
> I may be incorrect, but I think this happens because RPGInventory doesn't generate the entity id's correctly in their "load" function inside their main class: https://github.com/AbsolemJackdaw/rpginventory/blob/master/addonMasters/RpgMastersAddon.java.
> 
> Also, this actually helped me find another bug - replaceWitcheryWerewolfEntities being dependent on replaceVanillaCreepers.
> 
> In the real final version (which will be released today), **the replaceWitcheryWerewolfEntities config option may also need to be set to false**.

It didn’t just crash with entity conflict with rpg inventory, it also had the same crash with satisforestry, I also got a crash when spawning a werewolf with the witchery replacement on(different issue?)

**Comment by Rozmir-Rohi** [comment]
That issue is related to the one that I am fixing.

That issue happens because in the current version I released the code for registering the werewolf replacement entity is dependent on replaceVanillaCreepers. But it doesn't detect when it is set to false and tries to spawn a Witchery replacement werewolf when the entity isn't registered.

**Comment by Rozmir-Rohi** [comment]
@brandyyn  I've released a snapshot version on the Github releases.
Could you please test if it still crashes with both replaceWitcheryWerewolfEntities and replaceVanillaCreepers set to true.

**Comment by Rozmir-Rohi** [comment]
Since both of them are crashing I can tell that the config options are now working properly.
It's the entity ID conflict that now needs to be solved.

Please stay active, I'll see if I can get a unique entity ID to fix this.

**Comment by Rozmir-Rohi** [comment]
@brandyyn I've added a new snapshot release, could you please test this one as well?

If this one crashes, I'm giving up on fixing this issue and I'll add a note in the config files saying that the two config options aren't compatible with RPG inventory and Satisforestry.

**Comment by brandyyn** [comment]
> @brandyyn I've added a new snapshot release, could you please test this one as well?
> 
> If this one crashes, I'm giving up on fixing this issue and I'll add a note in the config files saying that the two config options aren't compatible with RPG inventory and Satisforestry.

WORKS =D

**Comment by brandyyn** [comment]
wait are werewolves supposed to turn back into villagers?

**Comment by Rozmir-Rohi** [comment]
They will eventually.

**Comment by brandyyn** [comment]
> Yes. They will at day time.

i noticed, the reason i ask is that they turn from like the human looking man into villagers ... hmmm would it be possible to customize what they turn back into? (could make it minecraft comes alive villagers ;0)

**Comment by brandyyn** [comment]
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/11356565/e51a98dd-0e9a-49fe-abeb-542fe11c0d26)
look, they fit in so well together

**Comment by Rozmir-Rohi** [comment]
This might be possible.
If there is a way for me to implement this I'll have to extend the real final release date to a couple of days later.

**Comment by brandyyn** [comment]
> This might be possible. If there is a way for me to implement this I'll have to extend the real final release date to a couple of days later.

very very much appreciated, you are once again, the best.

**Comment by Rozmir-Rohi** [comment]
No guarantee I will be able to add this though.

**Comment by brandyyn** [comment]
> No guarantee that I will be able to add this though.

ofcourse, it would be cool. and definitely my final request!
