### ISSUE TITLE
[Question]: Would it be possible to change the model of the wolf altar of witchery mod?

### ISSUE THREAD

**Issue by xronin01** [Rozmir-Rohi/mo-creatures-legacy#42]
![Screenshot_20240217-134441_PojavLauncher (Minecraft Java Edition for Android)_1](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/109928669/97d703a2-2000-4808-95fe-c808496fafe3)

**Comment by Rozmir-Rohi** [comment]
This might be possible using ASM to replace the model class file. But I still have to confirm this though.

**Comment by Rozmir-Rohi** [comment]
This is possible!

**Comment by Rozmir-Rohi** [comment]
Do you have any ideas for how the new wolf altar should look like?

I was thinking on something like a shrine to Hircine from Elder Scrolls (see below).
But the problem with this idea is that the deer head on the figure makes it look a bit like the Horned Huntsman from Witchery.

![Hircine Shrine](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/120696188/8fbf397d-b527-481d-8933-2e0938fa8bf4)

**Comment by xronin01** [comment]
My idea was just to make it more like the wolf from Mo' Creatures

**Comment by Rozmir-Rohi** [comment]
ok, I can work with that as the base idea.

I'll start working on the new model soon.

**Comment by Rozmir-Rohi** [comment]
Progress update:
![altar model front](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/120696188/cf90483a-ae14-478a-83a9-f1028aca2365)
![altar model side](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/120696188/c952a066-2596-4d41-92ee-5f6552b5e400)

**Comment by Rozmir-Rohi** [comment]
I've moved this feature to be its own mod, and it now has its own repository.

New repository for the Witchery Wolf Altar Replacement mod: https://github.com/Rozmir-Rohi/witchery-wolf-altar-replacement



Updates on progress can be found here: https://github.com/Rozmir-Rohi/witchery-wolf-altar-replacement/issues/1


Unfortunately, the completion date for the Witchery Wolf Altar Replacement mod is uncertain as I'm about to get busier with IRL things. The Witchery Wolf Altar Replacement mod may be finished anywhere from a week to a few months from now.
