### ISSUE TITLE
Bug with mobconfinement mod.

### ISSUE THREAD

**Issue by 167OSS** [Rozmir-Rohi/mo-creatures-legacy#43]
## What is the Bug?
When I use the mobconfinement mod to capture a pet scorpion and then release it and then capture it again, and repeat this many times and then reenter the save, the ground will show the scorpion for the number of times I have performed this operation

## How can I Reproduce this Bug?
Examples:
* Use  [
[unzipme.zip](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/14322857/unzipme.zip)
] with Mo' Creatures Legacy 
* Happens when [INSERT EVENT HERE]

## Screenshots
Screenshots are especially important for texture bugs.

## Additional Context
Example: Provide a link to a crash log or upload the text file for it.

**Comment by Rozmir-Rohi** [comment]
It appears that this actually happens for any tamed Mo' Creatures entity.

When you capture any tamed Mo' Creatures entity with mob confinement they don't go into the mob confinement. They are still there, just invisible.
When you reload the world the entity that was invisible becomes visible again. 

I'll still try to fix this though.

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.
