### ISSUE TITLE
Entity ID Conflict

### ISSUE THREAD

**Issue by 167OSS** [Rozmir-Rohi/mo-creatures-legacy#48]
[crash-2024-02-26_11.37.46-client.txt](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/14399375/crash-2024-02-26_11.37.46-client.txt)

**Comment by Rozmir-Rohi** [comment]
I'll fix this.
This is the last issue that I will fix for this project.

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.
I will re-upload the 1.1 version of the project with this fix on the Curseforge and Modrinth pages.
