### ISSUE TITLE
Crash when using turtle spawn egg

### ISSUE THREAD

**Issue by 167OSS** [Rozmir-Rohi/mo-creatures-legacy#49]
[crash-2024-02-27_19.43.24-client.txt](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/14418900/crash-2024-02-27_19.43.24-client.txt)

**Comment by Rozmir-Rohi** [comment]
I'll fix this one as well 😞.

Could you please do a test to see if you can find any other major bugs?
I don't want to have to keep coming back to fix things.

**Comment by 167OSS** [comment]
> I'll fix this one as well 😞.
> 
> Could you please do a test to see if you can find any other major bugs? I don't want to have to keep coming back to fix things.
For your request, as you handled mine. I'll do my best, but I'm not a dedicated mod tester, I don't know about JAVA coding or other programs used for testing, I can only make guessing moves within the game, and when I see that there are still people like you working on old mods and old versions like this, I'm very excited and touched, and I appreciate it! (Sorry for my bad English expression)

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.

I'll re-upload the 1.1 version with this fix to the Curseforge and Modrinth pages soon.


I'm extending support for bug fixes until the end of 23rd June 2024,  I will try to fix any bugs that are reported in this time.
My response times may vary as I will be busier with other things, but I will get to working on them eventually.
