### ISSUE TITLE
MoC_Spawn_List.cfg not working

### ISSUE THREAD

**Issue by xronin01** [Rozmir-Rohi/mo-creatures-legacy#50]
I put it all in false and it keeps spawning
[latest.log](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/14471061/latest.log)

# MoC Settings

####################
# ant
####################

ant {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# bear
####################

bear {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=4
    I:maxspawn=2
    I:minspawn=1
}

####################
# bee
####################

bee {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# bigcat
####################

bigcat {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=4
    I:maxspawn=2
    I:minspawn=1
}

####################
# biggolem
####################

biggolem {
    B:canspawn=false
    I:frequency=3
    I:maxchunk=1
    I:maxspawn=1
    I:minspawn=1
}

####################
# bird
####################

bird {
    B:canspawn=false
    I:frequency=12
    I:maxchunk=4
    I:maxspawn=3
    I:minspawn=2
}

####################
# boar
####################

boar {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=2
}

####################
# bunny
####################

bunny {
    B:canspawn=false
    I:frequency=3
    I:maxchunk=4
    I:maxspawn=3
    I:minspawn=2
}

####################
# butterfly
####################

butterfly {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=3
    I:maxspawn=3
    I:minspawn=1
}

####################
# crab
####################

crab {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# cricket
####################

cricket {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# crocodile
####################

crocodile {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# deer
####################

deer {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# dolphin
####################

dolphin {
    B:canspawn=false
    I:frequency=3
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# dragonfly
####################

dragonfly {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# duck
####################

duck {
    B:canspawn=false
    I:frequency=10
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# elephant
####################

elephant {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# firefly
####################

firefly {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# fishy
####################

fishy {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=6
    I:maxspawn=6
    I:minspawn=3
}

####################
# flamewraith
####################

flamewraith {
    B:canspawn=false
    I:frequency=5
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# fly
####################

fly {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# fox
####################

fox {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=2
    I:maxspawn=1
    I:minspawn=1
}

####################
# goat
####################

goat {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=3
    I:minspawn=1
}

####################
# hellrat
####################

hellrat {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# horsemob
####################

horsemob {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=3
    I:minspawn=1
}

####################
# jellyfish
####################

jellyfish {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# kitty
####################

kitty {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# komododragon
####################

komododragon {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# maggot
####################

maggot {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# mediumfish
####################

mediumfish {
    B:canspawn=false
    I:frequency=12
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=4
}

####################
# minigolem
####################

minigolem {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=2
    I:maxspawn=1
    I:minspawn=1
}

####################
# mole
####################

mole {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# mouse
####################

mouse {
    B:canspawn=false
    I:frequency=5
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# ogre
####################

ogre {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# ostrich
####################

ostrich {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# piranha
####################

piranha {
    B:canspawn=false
    I:frequency=10
    I:maxchunk=4
    I:maxspawn=6
    I:minspawn=1
}

####################
# raccoon
####################

raccoon {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# rat
####################

rat {
    B:canspawn=false
    I:frequency=7
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# ray
####################

ray {
    B:canspawn=false
    I:frequency=3
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# roach
####################

roach {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# scorpion
####################

scorpion {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# shark
####################

shark {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# silverskeleton
####################

silverskeleton {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# smallfish
####################

smallfish {
    B:canspawn=false
    I:frequency=12
    I:maxchunk=6
    I:maxspawn=6
    I:minspawn=2
}

####################
# snail
####################

snail {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# snake
####################

snake {
    B:canspawn=false
    I:frequency=2
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# turkey
####################

turkey {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# turtle
####################

turtle {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# werewolf
####################

werewolf {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=4
    I:minspawn=1
}

####################
# wildhorse
####################

wildhorse {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# wraith
####################

wraith {
    B:canspawn=false
    I:frequency=1
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# wwolf
####################

wwolf {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=4
    I:minspawn=1
}

####################
# wyvern
####################

wyvern {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=3
    I:minspawn=1
}

**Comment by xronin01** [comment]
https://github.com/quentin452/Mo-Creatures-Continuation/issues/11

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit. The entity spawn config file now works.
