### ISSUE TITLE
Pet Amulets not releasing the creature when right clicking

### ISSUE THREAD

**Issue by AnxiousRexy** [Rozmir-Rohi/mo-creatures-legacy#54]
## How can I Reproduce this Bug?
Examples:
* Use  [INSERT MODS HERE] with Mo' Creatures Legacy 
* Happens when [INSERT EVENT HERE]

## Screenshots
Screenshots are especially important for texture bugs.

## Additional Context
Example: Provide a link to a crash log or upload the text file for it.

**Comment by Rozmir-Rohi** [comment]
Which type of mob do you have in the Pet Amulet?
Are you the owner of the pet? Only owners of the pet can release them from the amulet.

**Comment by AnxiousRexy** [comment]
> Which entity do you have in the Pet Amulet? Also, are you the owner of the pet? Only owners of the pet can release them from the amulet.

My horse was in the amulet and I can not let it out of the amulet. I assume this happens to any pet

**Comment by Rozmir-Rohi** [comment]
I think that either the horse inside the amulet is bugged out or the amulet isn't recognising you as the horse's owner.
I've tested it with version 1.1 of the mod but I can't seem to replicate this issue by myself.


Could you hover your mouse cursor over the pet amulet and check that the player username in the "Owned by" part matches your player username (see picture below)?
Also could you please send me a screenshot of your view when you hover over the pet amulet?
![2024-07-24_18 18 41](https://github.com/user-attachments/assets/0f5cff2b-3198-4ab3-afaa-9e22ed754dd9)



In a separate world could you try taming a creature and using a Pet Amulet on it to get it inside the amulet and then try to release it again? Please let me know what result you get.


After the time you put the horse in the pet amulet, did you change from the original Mo' Creatures mod to Mo' Creatures Legacy or did you update Mo' Creatures Legacy?


If the owner name matches your player username and you didn't update/change MoCreatures, I could try going into your world to find out why it's happening:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If so please:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1. Put the pet amulet with the horse in a chest
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2. Give me the coordinates of the chest
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. Tell me any mods that is used in the world
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 4. Inside of one zip file, put your world and the config folder from .minecraft and send it through as a GitHub comment

**Comment by AnxiousRexy** [comment]
Nvm I was mistaking this issue with another fork my bad. But I did find a new issue. The mob spawn config file does not register my changes.

**Comment by Rozmir-Rohi** [comment]
No worries :grin:
I've recently fixed the spawn config not working in the development version. The fix will be featured in the next public release of the mod.
