### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Omgise** [Rozmir-Rohi/mo-creatures-legacy#59]
crash on the ocean
[crash-2024-12-14_19.50.22-server.txt](https://github.com/user-attachments/files/18135654/crash-2024-12-14_19.50.22-server.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/18135655/fml-client-latest.log)

**Comment by Rozmir-Rohi** [comment]
Fixed issue with recent commit.
The crash happened because a Jellyfish was trying to poison a Boat from Et Futurum Requiem.
